spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: pro


comment:
  avatar: /images/cat.jpg

#配置文件防止乱码
server:
  servlet:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  tomcat:
    uri-encoding: utf-8
  port: 8080
