spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong&useUnicode=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true

#日志
logging:
  level:
    root: info
    com.lb: debug
  file:
    path: log/myblog-dev.log


